#!/bin/bash

echo "Fine-Grained Personal Access Token Analysis"
echo "==========================================="
echo ""
echo "Token type: Fine-grained PAT (github_pat_...)"
echo ""
echo "Fine-grained tokens have repository-specific permissions."
echo "Even with 'Admin' access, you need explicit 'Issues: Write' permission."
echo ""
echo "To fix this:"
echo ""
echo "Option 1: Update your fine-grained token"
echo "1. Go to: https://github.com/settings/personal-access-tokens"
echo "2. Find your current token and click 'Edit'"
echo "3. Under 'Repository permissions' for PSPDFKit/nutrient-dws-client-python:"
echo "   - Issues: Read → Write"
echo "   - Pull requests: Read → Write (if needed)"
echo "4. Save changes"
echo ""
echo "Option 2: Create a classic token instead"
echo "1. Go to: https://github.com/settings/tokens/new"
echo "2. Create a classic token with 'repo' scope"
echo "3. Use: gh auth login"
echo "4. Paste the new classic token"
echo ""
echo "Classic tokens (ghp_...) have simpler, broader permissions."
echo "Fine-grained tokens (github_pat_...) need explicit permissions per repository."