#!/bin/bash

echo "Fixing GitHub CLI Authentication for Issue Creation"
echo "=================================================="
echo ""
echo "Current situation:"
echo "- GITHUB_TOKEN environment variable is set with limited permissions"
echo "- This is overriding GitHub CLI's stored credentials"
echo ""
echo "To fix this, run these commands:"
echo ""
echo "1. Temporarily unset the GITHUB_TOKEN environment variable:"
echo "   unset GITHUB_TOKEN"
echo ""
echo "2. Login to GitHub CLI with a new token that has issue write permissions:"
echo "   gh auth login"
echo ""
echo "   When prompted:"
echo "   - Choose: GitHub.com"
echo "   - Choose: HTTPS"
echo "   - Choose: Paste an authentication token"
echo "   - Generate a new token at: https://github.com/settings/tokens/new"
echo "   - Required scopes: 'repo' (or at least 'public_repo' + 'write:issues')"
echo "   - Paste the new token"
echo ""
echo "3. Verify the new authentication:"
echo "   gh auth status"
echo ""
echo "4. Test issue creation:"
echo "   gh issue create --repo PSPDFKit/nutrient-dws-client-python --title 'Test' --body 'Test'"
echo ""
echo "Alternative: If you want to keep using GITHUB_TOKEN:"
echo "- Generate a new token with 'repo' scope"
echo "- Export it: export GITHUB_TOKEN='new_token_with_repo_scope'"
echo ""
echo "Note: The gh CLI stored credentials take precedence over GITHUB_TOKEN when both exist."