#!/bin/bash

echo "GitHub Token Setup for Issue Creation"
echo "====================================="
echo ""
echo "Your current token can push to branches but not create issues."
echo "You need to create a new Personal Access Token with additional scopes."
echo ""
echo "Steps to create a new token:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://github.com/settings/tokens/new"
echo ""
echo "2. Give your token a descriptive name:"
echo "   Example: 'nutrient-dws-client-development'"
echo ""
echo "3. Set expiration (recommended: 90 days)"
echo ""
echo "4. Select the following scopes:"
echo "   ✓ repo (Full control of private repositories)"
echo "     - This includes:"
echo "       ✓ repo:status"
echo "       ✓ repo_deployment" 
echo "       ✓ public_repo"
echo "       ✓ repo:invite"
echo "       ✓ security_events"
echo "   ✓ workflow (if you need to update GitHub Actions)"
echo ""
echo "5. Click 'Generate token'"
echo ""
echo "6. Copy the generated token (it starts with 'ghp_')"
echo ""
echo "7. Run this command to update your GitHub CLI authentication:"
echo "   gh auth login"
echo ""
echo "   - Choose: GitHub.com"
echo "   - Choose: Paste an authentication token"
echo "   - Paste your new token"
echo ""
echo "Alternative: Set token as environment variable:"
echo "   export GITHUB_TOKEN='your_new_token_here'"
echo ""
echo "To verify your new token has the correct scopes:"
echo "   gh api user -H 'Accept: application/vnd.github.v3+json' --include | grep X-OAuth-Scopes"
echo ""
echo "The output should show: X-OAuth-Scopes: repo, workflow"
echo ""
echo "Once set up, you can create issues with:"
echo "   gh issue create --repo PSPDFKit/nutrient-dws-client-python --title 'Test' --body 'Test issue'"
echo ""

# Make the script provide current status
echo "Current authentication status:"
gh auth status

echo ""
echo "Checking if we can access the PSPDFKit org repos:"
gh api orgs/PSPDFKit/repos --paginate --jq '.[].name' | grep -E "^nutrient-dws-client-python$" || echo "Cannot access PSPDFKit repositories with current token"